### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by hiraniha** [tuya/tuya-home-assistant#72]
**Describe the bug**
I have two devices but only one has been detected

**Expected behavior**
I was expecting the device to be automatically detected

**Device info**
{
  "result": {
    "active_time": 1625390602,
    "biz_type": 0,
    "category": "pir",
    "create_time": 1625390602,
    "icon": "smart/icon/ay1536534747810ekKBj/33e050831a2f667fcae9bff8aa5ec73b.png",
    "id": "675063713c6105dd66f5",
    "ip": "101.180.23.20",
    "lat": "-33.7066916",
    "local_key": "a4f88ff1d63fb068",
    "lon": "150.9076874",
    "name": "DET102HA",
    "online": true,
    "owner_id": "31807239",
    "product_id": "oapo5mmfbcr2y7ox",
    "product_name": "DET102HA",
    "status": [],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu16227858687542g6fx",
    "update_time": 1625394196,
    "uuid": "675063713c6105dd66f5"
  },
  "success": true,
  "t": 1625405263841
}

**Device specifications**
{
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1625405386590
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by cichy45** [comment]
I have update. 

Tuya Local V2 works correctly on newest core-2021.6.6 but does not work on core-2021.3.3. 

If you face any issues try to upgrade. Issue can be closed @hiraniha - maybe this information about HA Core version should be added to setup guide?

**Comment by hiraniha** [comment]
I am on the following 

core-2021.6.6
supervisor-2021.06.6

**Comment by hiraniha** [comment]
@cichy45 

I have the following 

 @cichy

I have the following 

core-2021.6.6
supervisor-2021.06.6

**Comment by tsutsuku** [comment]
@hiraniha The device needs to standardize, now it is fixed. You can try again.

**Comment by hiraniha** [comment]
@tsutsuku 

I can confirm the PIR has now been detected as a device with one entity

![image](https://user-images.githubusercontent.com/73940881/124864568-802b3500-dffc-11eb-946e-36bb4339a05e.png)

However even when the device and Tuya app show there is a detection of movement, HA is still show it as Clear

What can I provide to investigate that further?

**Comment by hiraniha** [comment]
@tsutsuku 

When I use the IOT platform and query the device details I see this section go from

    "status": [
      {
        "code": "pir",
        "value": "none"
      }
    ],
    
to

    "status": [
      {
        "code": "pir",
        "value": "pir"
      }
    ],

**Comment by tsutsuku** [comment]
@hiraniha Get it, we will fix it soon.

**Comment by hiraniha** [comment]
@tsutsuku 

Any update?

**Comment by hiraniha** [comment]
@tsutsuku

I saw the v1.3.2 had been released, I have tested on that and the PIR is now working as expected for the detection.

Will HA have all the other option included like changing sensitivity, on period etc?

**Comment by hiraniha** [comment]
Thanks I realised I never closed this issue
